//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistrictsInTown.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public int Id { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public double Score { get; set; }
        public string Keyword { get; set; }
        public string Source { get; set; }
    }
}
